CREATE TABLE PUBLIC_RECORDS
(
  AADHAR_NO INT NOT NULL,
  NAME CHAR(20) NOT NULL,
  AGE INT NOT NULL,
  BLOOD_GROUP CHAR(2) NOT NULL,
  WORK_INFORMATION VARCHAR(30) NOT NULL,
  CONTACT_NUMBER INT NOT NULL,
  CURRENT_HEALTH_STATUS VARCHAR(40) NOT NULL,
  NUMBER_OF_FAMILY_MEMBERS INT NOT NULL,
  PRIMARY KEY (AADHAR_NO)
);

CREATE TABLE ZONE
(
  WARD_NO INT NOT NULL,
  MLA CHAR(20) NOT NULL,
  NUMBER_OF_RESIDENTS INT NOT NULL,
  POPULATION_DENSITY INT NOT NULL,
  SANITISATION_STATUS DATE NOT NULL,
  NUMBER_OF_COVID19_CASES INT NOT NULL,
  PRIMARY KEY (WARD_NO)
);

CREATE TABLE COVID19_ACTIVE
(
  HEALTH_CARD_NO INT NOT NULL,
  BODY_TEMPERATURE FLOAT NOT NULL,
  BLOOD_OXYGEN_LEVEL FLOAT NOT NULL,
  OTHER_HEALTH_PROBLEMS VARCHAR(40) NOT NULL,
  OTHER_SYMPTOMS VARCHAR(40) NOT NULL,
  BREATHING_STATUS CHAR(10) NOT NULL,
  AADHAR_NO INT NOT NULL,
  PRIMARY KEY (HEALTH_CARD_NO),
  FOREIGN KEY (AADHAR_NO) REFERENCES PUBLIC_RECORDS(AADHAR_NO)
);

CREATE TABLE LIVES_IN
(
  LOCATION VARCHAR(40) NOT NULL,
  STREET VARCHAR(30) NOT NULL,
  PINCODE INT NOT NULL,
  AADHAR_NO INT NOT NULL,
  WARD_NO INT NOT NULL,
  PRIMARY KEY (AADHAR_NO),
  FOREIGN KEY (AADHAR_NO) REFERENCES PUBLIC_RECORDS(AADHAR_NO),
  FOREIGN KEY (WARD_NO) REFERENCES ZONE(WARD_NO)
);

CREATE TABLE DENGUE_ACTIVE
(
  HEALTH_CARD_NO INT NOT NULL,
  BODY_TEMPERATURE FLOAT NOT NULL,
  BLOOD_PRESSURE_LEVEL FLOAT NOT NULL,
  BLOOD_PLATELET_COUNT INT NOT NULL,
  URGENT_REQUIREMENT_OF_BLOOD CHAR NOT NULL,
  OTHER_HEALTH_PROBLEMS VARCHAR(40) NOT NULL,
  OTHER_SYMPTOMS VARCHAR(40) NOT NULL,
  AADHAR_NO INT NOT NULL,
  PRIMARY KEY (HEALTH_CARD_NO),
  FOREIGN KEY (AADHAR_NO) REFERENCES PUBLIC_RECORDS(AADHAR_NO)
);

CREATE TABLE CLUB_MEMBER_RECORDS
(
  NAME CHAR(20) NOT NULL,
  MEMBERSHIP_ID INT NOT NULL,
  JOIN_DATE DATE NOT NULL,
  POSITION CHAR NOT NULL,
  AGE INT NOT NULL,
  AVAILABILITY_STATUS CHAR NOT NULL,
  AADHAR_NO INT NOT NULL,
  PRIMARY KEY (MEMBERSHIP_ID),
  FOREIGN KEY (AADHAR_NO) REFERENCES PUBLIC_RECORDS(AADHAR_NO)
);

CREATE TABLE MEDICAL_HELP_RECORDS
(
  MEDICAL_ID INT NOT NULL,
  NAME CHAR(20) NOT NULL,
  PROFESSION CHAR(27) NOT NULL,
  ADDRESS VARCHAR(30) NOT NULL,
  AVAILABILITY_STATUS CHAR NOT NULL,
  PRIMARY KEY (MEDICAL_ID)
);

CREATE TABLE MEDICAL_WORKERS
(
  AADHAR_NO INT NOT NULL,
  MEDICAL_ID INT NOT NULL,
  PRIMARY KEY (AADHAR_NO),
  FOREIGN KEY (AADHAR_NO) REFERENCES PUBLIC_RECORDS(AADHAR_NO),
  FOREIGN KEY (MEDICAL_ID) REFERENCES MEDICAL_HELP_RECORDS(MEDICAL_ID)
);

CREATE TABLE HOSPITAL_INFORMATION
(
  REGISTRATION_NO INT NOT NULL,
  HOSPITAL_NAME CHAR(20) NOT NULL,
  NO_OF_GENERAL_BEDS INT NOT NULL,
  NO_OF_COVID19_BEDS_FREE INT NOT NULL,
  RT_PCR_TEST_AVAILABILITY boolean NOT NULL,
  NO_OF_FULL_TIME_DOCTORS INT NOT NULL,
  NO_OF_DENGUE_BEDS_FREE INT NOT NULL,
  LOCATION VARCHAR(30) NOT NULL,
  STREET VARCHAR(20) NOT NULL,
  PINCODE INT NOT NULL,
  WARD_NO INT NOT NULL,
  PRIMARY KEY (REGISTRATION_NO),
  FOREIGN KEY (WARD_NO) REFERENCES ZONE(WARD_NO)
);

CREATE TABLE ISOLATION_CENTRE_DETAILS
(
  CENTRE_CODE INT NOT NULL,
  ADDRESS VARCHAR(30) NOT NULL,
  SIZE_OF_ROOM FLOAT NOT NULL,
  TOTAL_COST_PER_DAY FLOAT NOT NULL,
  ACCOMMODATION_STRENGTH INT NOT NULL,
  NO_OF_VACANCIES INT NOT NULL,
  LOCATION VARCHAR(30) NOT NULL,
  STREET VARCHAR(20) NOT NULL,
  PINCODE INT NOT NULL,
  WARD_NO INT NOT NULL,
  PRIMARY KEY (CENTRE_CODE),
  FOREIGN KEY (WARD_NO) REFERENCES ZONE(WARD_NO)
);

CREATE TABLE REQUIREMENTS
(
  NAME CHAR(20) NOT NULL,
  FOOD_ITEMS_NEEDED VARCHAR(40) NOT NULL,
  RATION_NEEDED VARCHAR(30) NOT NULL,
  INCOME_GROUP CHAR(10) NOT NULL,
  AADHAR_NO INT NOT NULL,
  WARD_NO INT NOT NULL,
  PRIMARY KEY (AADHAR_NO),
  FOREIGN KEY (AADHAR_NO) REFERENCES PUBLIC_RECORDS(AADHAR_NO),
  FOREIGN KEY (WARD_NO) REFERENCES ZONE(WARD_NO)
);

CREATE TABLE COVID19_RECOVERED
(
  DATE_OF_RECOVERY DATE NOT NULL,
  NAME CHAR NOT NULL,
  AGE INT NOT NULL,
  CURRENT_HEALTH_STATUS CHAR NOT NULL,
  BLOOD_GROUP CHAR NOT NULL,
  AADHAR_NO INT NOT NULL,
  PRIMARY KEY (AADHAR_NO),
  FOREIGN KEY (AADHAR_NO) REFERENCES PUBLIC_RECORDS(AADHAR_NO)
);

CREATE TABLE DOCTORS
(
  NAME CHAR(20) NOT NULL,
  CHAMBER_LOCATION VARCHAR(30) NOT NULL,
  DUTY_HOURS CHAR(10) NOT NULL,
  AVAILABILITY_STATUS boolean NOT NULL,
  DEGREE CHAR(30) NOT NULL,
  CHAMBER_STREET VARCHAR(20) NOT NULL,
  CHAMBER_PINCODE INT NOT NULL,
  MEDICAL_ID INT NOT NULL,
  PRIMARY KEY (MEDICAL_ID),
  FOREIGN KEY (MEDICAL_ID) REFERENCES MEDICAL_HELP_RECORDS(MEDICAL_ID)
);

CREATE TABLE AMBULANCE_DETAILS
(
  REGISTRATION_NO INT NOT NULL,
  OWNER_NAME CHAR NOT NULL,
  EQUIPMENTS_AVAILABLE VARCHAR(30) NOT NULL,
  PARKING_LOCATION VARCHAR(20) NOT NULL,
  AVAILABILITY_STATUS boolean NOT NULL,
  MEDICAL_ID INT NOT NULL,
  PRIMARY KEY (REGISTRATION_NO),
  FOREIGN KEY (MEDICAL_ID) REFERENCES MEDICAL_HELP_RECORDS(MEDICAL_ID)
);